#!/usr/bin/env sh
confd="/etc/opt/simplex"

# Check if server has been initialized
if [ ! -f "$confd/smp-server.ini" ]; then
	smp-server init -l --ip `curl ifconfig.me`
fi

# Finally, run smp-sever. Notice that "exec" here is important:
# smp-server replaces our helper script, so that it can catch INT signal
smp-server start
